<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-NOBQL6Q" name="com.qa.hrm.TestCases.GeneralInfoTestCase" tests="1" failures="0" timestamp="2020-04-07T16:57:16 IST" time="5.032" errors="1">
  <testcase name="validateGenralInfo" time="5.032" classname="com.qa.hrm.TestCases.GeneralInfoTestCase">
    <error type="org.testng.internal.reflect.MethodMatcherException" message="
[public void com.qa.hrm.TestCases.GeneralInfoTestCase.validateGenralInfo(java.lang.String,java.lang.CharSequence[],java.lang.String,java.lang.String,java.lang.String,java.lang.CharSequence[],java.lang.CharSequence[],java.lang.String,java.lang.String) throws java.io.IOException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: validateGenralInfo([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=[Ljava.lang.CharSequence;, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=4, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=5, type=[Ljava.lang.CharSequence;, declaredAnnotations=[]}, Parameter{index=6, type=[Ljava.lang.CharSequence;, declaredAnnotations=[]}, Parameter{index=7, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=8, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) Ankita,(java.lang.String) 9.99999999E8,(java.lang.String) ankita@orageHRM.com,(java.lang.String) Paharganj,(java.lang.String) Delhi,(java.lang.String) 568878.0,(java.lang.String) 565455.0,(java.lang.String) Delhi]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void com.qa.hrm.TestCases.GeneralInfoTestCase.validateGenralInfo(java.lang.String,java.lang.CharSequence[],java.lang.String,java.lang.String,java.lang.String,java.lang.CharSequence[],java.lang.CharSequence[],java.lang.String,java.lang.String) throws java.io.IOException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: validateGenralInfo([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=[Ljava.lang.CharSequence;, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=4, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=5, type=[Ljava.lang.CharSequence;, declaredAnnotations=[]}, Parameter{index=6, type=[Ljava.lang.CharSequence;, declaredAnnotations=[]}, Parameter{index=7, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=8, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) Ankita,(java.lang.String) 9.99999999E8,(java.lang.String) ankita@orageHRM.com,(java.lang.String) Paharganj,(java.lang.String) Delhi,(java.lang.String) 568878.0,(java.lang.String) 565455.0,(java.lang.String) Delhi]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:43)
at org.testng.internal.Parameters.injectParameters(Parameters.java:909)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:34)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- validateGenralInfo -->
  <system-out/>
</testsuite> <!-- com.qa.hrm.TestCases.GeneralInfoTestCase -->
